name: Bazel Release

on:
  release:
    types: [published]

jobs:
  # A release archive is required for bzlmod
  # See: https://blog.bazel.build/2023/02/15/github-archive-checksum.html
  bazel-release-archive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4.1.1
      - run: git archive $GITHUB_REF -o "yaml-cpp-${GITHUB_REF:10}.tar.gz"
      - run: gh release upload ${GITHUB_REF:10} "yaml-cpp-${GITHUB_REF:10}.tar.gz"
        env:
          GH_TOKEN: ${{ github.token }}
